# Generated by Django 4.1.13 on 2024-07-30 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('age', models.IntegerField(default=0)),
                ('avatar', models.URLField(blank=True, null=True)),
                ('balance', models.FloatField(default=0.0)),
                ('is_premium', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(auto_now_add=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('streak', models.CharField(blank=True, max_length=255, null=True)),
                ('telegram_id', models.CharField(max_length=255, unique=True)),
                ('top_group', models.IntegerField(default=0)),
                ('top_percent', models.IntegerField(default=0)),
                ('wallet', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
